### PR TITLE
Atom-like structures

### PR DESCRIPTION
**Pull request by crisptrutski**
"Make binding portions of your reactive state to your synchronous UI a cinch"

Create/wrap atoms to sync with Firebase refs, using the strategy of your choice.

### CODE REVIEW

**Comment by crisptrutski** [comment]
@martinklepsch thought you might be interested / have input? 

Think this sort of thing would be ideal for beginners - giving them some durable multi user legs for basic applications with the slew of react-based clojurescript libs.

**Comment by podviaznikov** [comment]
So all I need to do is to call `brute-atom` with any firebase node and I'll have local automatically synced atom (with all firebase state applied)?
And I can use this atom as normal clojure atom. Is this correct?

**Comment by crisptrutski** [comment]
Yes, `brute-atom` returns an actual atom, with sync in both directions via appropriate observer mechanism.

Shortcomings / gotchas :

1. Very inefficient for large state (always writes everything, and also rebuilds the entire immutable map on every update)
2. It wipes out any firebase meta data (eg priority) due to doing a too level write alway
3. Since clojurescript does not have am order pressing map, cannot rely on priority or query over ref to order the keys.
4. Related to 3, there is also no translation of clojure vectors to pseudo-incrementing firebase maps. This has advantage of making 3 less of an issue, but means that multi agent updates are more brittle.
4. Slightly more latency that `reset-atom`, but the trade off is that `reset-atom` returns a custom datatype instead of actual atom. On clojurescript atoms have a protocol so no real loss, but not the case in clojure  (you can see my awkward crutch of definingown  protocols to use instead, and extending those back to regular aroms)
5. Watch out for having multiple atoms covering same portion of state, they don't coordinate and there can be jitter or data loss

Despite all those disclaimers - it's still suitable for lots of cases - for example I tried it against a 'todomvc' example and did not have any issues.

Also believe some further work could improve this aspects considerably.

**Comment by podviaznikov** [comment]
This is great feature and exactly what I want. I use your library with Clojure on the server for small amount of state sync.
Right now I'm just listening on `value` and swap new state into the atom. `brute-atom` sounds good to me.
+1 for merging this.

**Comment by crisptrutski** [comment]
@podviaznikov merged :tada:

**Pull request merged**
