### PR TITLE
Add Oauth methods to CLJS build

### PR DESCRIPTION
**Pull request by crisptrutski**
Publishes as `0.0.9`

### CODE REVIEW

**Comment by crisptrutski** [comment]
Closes #65

**Comment by flyboarder** [comment]
There is one small issue with the popup/redirect functions, providers may also be passed an options map which is currently missing, for example this is required for apps to get users email from google, instead of just the google:uid.

`(.authWithOAuthPopup ref "google" #js{:scope "email"})`

**Comment by crisptrutski** [comment]
Thanks for point this out, ammending quickly

**Comment by crisptrutski** [comment]
Closed by 21076ac5f61c0377ea7719c60536d048d02f6b07

**Pull request merged**
